### ISSUE TITLE
EPIC: Support HA

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#42]
The below items should be broken out into separate issues, once we get closer to working on this feature

### Phase 1
- [x] Provide fault tolerance at 2+ instances.
- [x] Point to an external SQL database like MySQL, Postgres, or etcd 3. Users can then use RDS or other SQL solution. (Only PostgreSQL 10.7-11.5 as of v0.10.0 release)
- [x] Support etcd as a backend through manual configuration by user
  - [x] Need to expose configurations params needed for etcd. Implement as generic framework that supports all paras in the form of  `--<component>-<component flag>`
- [x] Support peer discover that Rancher 2 has. Can reuse the framework from norman, but need to implement the component that does the discovery
- [x] Add logic in agents to allow for auto-discovery of all api nodes. Then, use client-side logic to round robin between them if leader goes does. Effectively  
### Phase 2
- [x] Embed ~etcd~ dqlite (experimental in v1.0.0 release) in k3s image and simply SSL setup for "easy" HA configuration

**Comment by Sh4d1** [comment]
Could https://github.com/rqlite/rqlite be a alternative to etcd?

**Comment by xinity** [comment]
AFAIK @Sh4d1 k3s has already dropped etcd for sqlite 😏

**Comment by jamesxia20181001** [comment]
Can K3S currently support HA when using sqlite3? If it is not currently supported, is there any plan support in the future?
Does K3S still need to use ETCD now and in the future?

**Comment by cjellick** [comment]
k3s doesnt support HA at all yet. When it does, it will (at least initially) do so with etcd as a the datastore. But, we have plans for making this seemless and painless. Basically, it should be pretty transparent to the operator. You wont have to manage etcd yourself.

**Comment by warmchang** [comment]
Package the etcd in the single k3s binary, just like the containerd/Flannel?

**Comment by schmitch** [comment]
can't etcd run as a docker image inside k8s? actually kubeadm starts etcd within a kubelet manifest file, wouldn't that be possible aswell? so k3s just needs to write a manifest file every boot and put the etcd image into the airgap tar. so the only thing k3s still needs to handle is how to get all the certificates distributed.

**Comment by nikatjef** [comment]
I would like to second the suggestion for rqlite for the HA system.  For those not familiar with it, rqlite is a raft'd SQLite 3.  It uses raft to provide for a pretty high performance clustered SQLite DB.

More details can be found at;
  https://github.com/rqlite/rqlite

**Comment by mildred** [comment]
There is also Consul from Hashicorp that is very similar to etcd but far more easy to manage. Where I work, we managed automatically etcd clusters and Consul clusters, and Consul is really nice to operate from an automation point of view. It can automatically upgrade from a blank state to a clustered state. To the contrary, etcd needs to be started in the right configuration directly, and this requires synchronization beforehand that's difficult to have since etcd is not there. In the end, we managed to automatically operate etcd using Consul as preexisting layer.

**Comment by brokenjacobs** [comment]
would HA in this design require 3 nodes? 2 nodes would be rather nice for many of our applications.

**Comment by proegssilb** [comment]
I notice the v0.6 release added support for postgresql/mysql. The other part of this for 0.7 is support for multiple k3s masters?

**Comment by ChrisRx** [comment]
I've been working on a project that uses a gossip network and an embedded etcd binary to make working with HA etcd clusters easier.  I wanted to throw it out there in case there was interest in using it for something like this:

https://github.com/criticalstack/e2d

**Comment by Sebastien-HATTON** [comment]
Suggestion for the HA system : Consul (Hashicorp)

**Comment by Jeyanthinath** [comment]
Hope this would be releasing on Milestone 1.0, we can't able to push this stack into our production iot systems , because of HA unavailability.

**Comment by sandys** [comment]
I want to link to another feature request - the first step should be to investigate eliminating sqlite entirely . etcd can be embedded into the k3s binary just like sqlite in non-HA mode.

That will make the code easier to switch to an external HA etcd. 

https://github.com/rancher/k3s/issues/845

**Comment by davidnuzik** [comment]
v1.0.0 will be released shortly. Please reference the updated k3s docs here: https://rancher.com/docs/k3s/latest/en/

We describe the various configuration options to set up HA if some down time for the control plane is not permitted: https://rancher.com/docs/k3s/latest/en/installation/ha/

The docs have also been updated to address other install options.
Thank you everyone for all of your support!
